export type CaseStudy = {
  slug: string; client: string; sector: string; market: string; practices: string;
  title: string; challenge: string; work: string; deliverables: string[]; outcome: string;
  image: string; related: string;
};

export const CASE_STUDIES: CaseStudy[] = [
  { slug: "payments-entry", client: "AsterPay", sector: "Payments", market: "Nigeria, Kenya and Ghana", practices: "Intelligence + Institutions", title: "Building a smarter route into three fast-moving payments markets", challenge: "A global payments company needed to decide whether and how to enter three fast-moving markets. It had strong technology but an incomplete picture of licensing pathways, local competitors and the practical differences between each market.", work: "Sovran built a market-by-market entry picture covering customer segments, competitive position, payment habits, regulatory pathways and local partner options. We then mapped 42 relevant regulators, industry bodies and potential partners, and designed an engagement plan for the first twelve months.", deliverables: ["Sequenced three-market entry plan", "Regulatory action tracker", "Partner selection criteria", "Board-ready investment case"], outcome: "The client prioritised Kenya for first launch, adapted its product proposition for Nigeria and deferred Ghana pending a licensing change. The original three simultaneous entries became a controlled two-stage programme.", image: "/images/case-studies/Case-study_Asterpay.avif", related: "What regulatory fragmentation means for cross-border growth" },
  { slug: "infrastructure-investment", client: "Northline Capital", sector: "Infrastructure", market: "East Africa", practices: "Intelligence + Strategy", title: "Testing an infrastructure opportunity against freight corridor constraints", challenge: "An investment platform was assessing a multi-country freight-corridor opportunity. The opportunity was attractive on paper, but its assumptions did not yet account for border delays, port capacity, concession terms or local operator incentives.", work: "Sovran tested the investment case against operating conditions through interviews, traffic and trade-flow analysis, corridor scenarios and a map of decisions controlled by public agencies and concession holders.", deliverables: ["Commercial diligence report", "Scenario model", "Stakeholder map", "Phased investment recommendation"], outcome: "The investor narrowed its initial scope to two linked assets with clearer demand evidence, and used the work to structure conditions before capital deployment.", image: "/images/case-studies/development_finance-case.avif", related: "Infrastructure opportunities beyond major cities" },
  { slug: "logistics-expansion", client: "Axis Freight", sector: "Logistics", market: "West Africa", practices: "Strategy + Delivery", title: "Launching two regional hubs through one coordinated delivery programme", challenge: "A regional logistics business had won new enterprise clients, but country-by-country expansion was creating inconsistent service levels, duplicate vendor contracts and unclear accountability.", work: "Sovran designed a regional operating model around common service standards, local execution rights and a single view of network performance, then supported the first rollout waves with a delivery office and weekly decision rhythm.", deliverables: ["Network expansion strategy", "Operating-model blueprint", "Rollout plan", "Performance dashboard"], outcome: "The company reduced duplicate supplier arrangements, introduced a consistent service scorecard and launched two new hubs using the same delivery playbook.", image: "/images/case-studies/financial_services-case.avif", related: "Three signals reshaping East African logistics" },
  { slug: "digital-infrastructure", client: "National Digital Services Office", sector: "Public sector", market: "West Africa", practices: "Institutions + Delivery", title: "Aligning institutions around a shared digital infrastructure programme", challenge: "A public institution was planning a shared digital identity and service-access programme. The technical case was strong, but agencies had different mandates, data responsibilities and concerns about readiness.", work: "Sovran established the institutional picture before launch: mandates, decision rights, citizen journeys, data-governance questions and delivery dependencies. We supported a cross-agency programme office and clear public communication.", deliverables: ["Stakeholder and mandate map", "Programme governance model", "Implementation roadmap", "Communications framework"], outcome: "Disconnected agency plans became one agreed roadmap, with a shared governance group and a first set of priority services ready for piloting.", image: "/images/case-studies/public_sector-case.avif", related: "Digital identity and the next phase of public infrastructure" },
  { slug: "financial-transformation", client: "Harbour Bank Group", sector: "Financial services", market: "Southern Africa", practices: "Strategy + Delivery", title: "Refocusing a regional transformation around the customer journey", challenge: "A regional bank needed to improve how it served growing small-business customers. The journey crossed sales, credit, operations and digital channels without a shared owner.", work: "Sovran mapped the end-to-end small-business journey, identified where customers dropped out and helped leaders select a smaller set of improvements that could be delivered in sequence.", deliverables: ["Customer-journey diagnosis", "Target operating model", "Prioritised roadmap", "Benefits and delivery governance"], outcome: "The bank redirected its conceptual transformation budget to the three journey changes with the clearest customer and operational case, supported by named executive owners and quarterly measures.", image: "/images/case-studies/case-study-card-texture.png", related: "Local context is not a footnote to strategy" },
];
