export type PerspectiveDetail = {
  image: string;
  published: string;
  sections: { id: string; title: string; paragraphs: string[]; bullets?: string[] }[];
  quote: string;
  takeaway: string;
};

export const PERSPECTIVE_DETAILS: Record<string, PerspectiveDetail> = {
  "nigerias-next-digital-infrastructure-cycle": {
    image: "/images/intelligence/Blog thumbnail-Digital Infrastructure.avif", published: "21 August 2026",
    sections: [
      { id: "shared-layer", title: "The opportunity is in the shared layer", paragraphs: ["Nigeria’s digital market is often described through individual sectors: fintech, connectivity, identity, commerce and public services. The more important development is the way these systems are beginning to depend on one another. A payment product relies on identity, reliable connectivity and usable data. A public service increasingly relies on many of the same rails.", "This changes the unit of analysis. A company assessing demand cannot look only at the customers it can acquire. It must understand the shared infrastructure beneath the proposition, who governs it and where a dependency can become a bottleneck."], bullets: ["Identity and consent systems that can be trusted across services", "Reliable payment and settlement connections", "Interoperable public and private interfaces", "Operating partners able to resolve failures locally"] },
      { id: "commercial-map", title: "Build the infrastructure map before the growth plan", paragraphs: ["A conventional growth plan starts with addressable demand and moves quickly to channels, pricing and acquisition. In an infrastructure-dependent market, that sequence can hide the conditions that determine whether the service will work consistently.", "The better starting point is a dependency map. For each critical service, identify the owner, service level, governing rule and practical route for resolving an exception. That map should sit beside the commercial model and be tested with the same discipline."], bullets: ["Which infrastructure must work before the first customer can be served?", "Which decisions are controlled by a regulator or public institution?", "Where does service reliability depend on a third party?", "What can the local operating team change without escalation?"] },
      { id: "sequence", title: "Sequence the opportunity", paragraphs: ["The strongest entry may not be the largest use case. It may be the service with the clearest user problem, the fewest unresolved dependencies and the best route to institutional support. A focused first use case creates evidence that can justify the next layer of investment.", "For institutions, sequencing also protects trust. A programme can demonstrate reliability through a small number of valuable services before expanding into more sensitive or complex journeys."], bullets: ["Choose one service problem with visible user value", "Resolve ownership and escalation before launch", "Measure reliability as well as adoption", "Expand only when the underlying rails can support the next use case"] },
    ], quote: "The practical opportunity is not simply more technology. It is better coordination between the organisations that own the infrastructure, regulate it and depend on it.", takeaway: "Treat digital infrastructure as a connected operating system. Map the dependencies, choose a focused service problem and let evidence determine the next stage of growth."
  },
  "why-market-entry-fails-after-strategy": {
    image: "/images/intelligence/Blog thumbnail-Market entry.avif", published: "14 August 2026",
    sections: [
      { id: "approval-gap", title: "Approval creates a new set of decisions", paragraphs: ["A market-entry deck usually answers where to enter, why the opportunity is attractive and how much the organisation expects to invest. Once the board approves it, a different set of questions becomes urgent: which licence comes first, which partner can be trusted, who can adapt the offer and what the local team is allowed to decide.", "These are not details to be delegated after the strategy. Together they form the route by which the strategy becomes operational. When they are absent, teams fill the gap with assumptions and progress becomes a sequence of escalations."], bullets: ["The first customer and channel", "The first regulatory dependency", "The first local hire or operating partner", "The owner of every unresolved launch condition"] },
      { id: "conditions", title: "Replace the launch date with launch conditions", paragraphs: ["Dates are useful for coordination, but they can create false confidence. A launch can be on schedule while its essential conditions remain unresolved. Teams then compensate with temporary workarounds that become expensive permanent features.", "A stronger plan states what must be true before each commitment is made. Some conditions concern regulation, others concern product readiness, distribution, service support or local authority. The sequence should show which commitments are reversible and which create long-term exposure."], bullets: ["Licence or formal approval confirmed", "Product adaptation tested with real users", "Partner incentives and accountability agreed", "Exception handling proven under local conditions"] },
      { id: "monday-test", title: "Use the Monday-morning test", paragraphs: ["Ask the market team what it would do first next Monday. A useful answer names an action, an owner, the evidence required and the decision that follows. A vague answer—continue stakeholder engagement, refine the proposition, progress licensing—signals that the plan is still conceptual.", "The test is intentionally practical. It reveals where the strategy has not assigned authority, where a dependency has no owner and where a large workstream needs to become a smaller decision."], bullets: ["What action happens first?", "Who has authority to take it?", "What evidence will change the next decision?", "When will the team stop, adapt or commit further?"] },
    ], quote: "If the market team cannot say what it will do next Monday, the strategy has not yet become a route to market.", takeaway: "Design implementation while the strategy is still being made. Name launch conditions, owners and decision rights before the organisation commits to a public date."
  },
  "the-new-competitive-landscape-for-african-payments": {
    image: "/images/intelligence/Blog thumbnail-Payments.avif", published: "7 August 2026",
    sections: [
      { id: "competition", title: "Competition has moved beyond transaction volume", paragraphs: ["Scale still matters in payments, but it no longer explains the full competitive position. Merchants and consumers judge providers through reliability, settlement speed, dispute handling, onboarding and the fit between a product and the way money actually moves.", "This makes apparently similar markets behave differently. A proposition built around card acceptance may meet a different problem from one built around account transfers, mobile money, cash conversion or cross-border settlement."], bullets: ["Trust at the moment a transaction fails", "Distribution into the customer’s existing workflow", "Regulatory fit and compliance capability", "Settlement reliability and usable reconciliation"] },
      { id: "job", title: "Start with the customer’s job", paragraphs: ["The question is not simply where a product can launch. It is which job a customer is trying to complete and why the current route is costly, uncertain or slow. That job may be collecting from customers, paying suppliers, reconciling sales or moving money between markets.", "A precise customer job clarifies which features matter and which partnerships are strategic. It also prevents a provider from reproducing its home-market proposition in a context where the underlying friction is different."], bullets: ["Observe the complete payment journey, including exceptions", "Measure the cost of delay and uncertainty, not only fees", "Separate the buyer, user and beneficiary", "Test the proposition with the support and compliance model included"] },
      { id: "operating-model", title: "The operating model is part of the product", paragraphs: ["Payment products are often presented as software while much of the customer experience is delivered through operations. Compliance review, merchant support, liquidity, settlement and dispute resolution determine whether a promise survives contact with the market.", "Providers should design these capabilities before announcing scale. Local partners can extend reach, but only when incentives, service levels and escalation rights are explicit."], bullets: ["Give local teams clear decision rights", "Make settlement and support performance visible", "Treat compliance as a product capability", "Plan partner governance before volume arrives"] },
    ], quote: "The winning question is not ‘Where can we launch?’ but ‘Which job are we helping this customer complete better?’", takeaway: "Build around a specific customer job, then design distribution, compliance and support as visible parts of the proposition."
  },
  "regulatory-fragmentation-cross-border-growth": {
    image: "/images/intelligence/Blog thumbnail-Cross border.avif", published: "31 July 2026",
    sections: [
      { id: "commercial", title: "Regulation is part of the commercial model", paragraphs: ["Cross-border expansion is often split into a growth workstream and a legal workstream. That separation is convenient internally but misleading in the market. Licensing scope can shape the customer proposition; data rules can change the operating model; settlement requirements can alter unit economics.", "The regulatory pathway should therefore be evaluated with the same questions as any commercial choice: what value does it enable, what commitment does it require and what uncertainty remains?"], bullets: ["Licence scope and sequencing", "Data location and transfer requirements", "Capital, settlement and reporting obligations", "Local governance and accountable officers"] },
      { id: "fragmentation", title: "Fragmentation changes the route, not only the timetable", paragraphs: ["When rules differ across markets, the default response is often to add time to a regional launch plan. But fragmentation can require a different structure entirely: separate entities, different partners, a narrower product or a staged customer proposition.", "A plan should distinguish between requirements that can be handled through a common regional capability and those that require local authority or infrastructure. This is how the organisation avoids building a central model that local teams must constantly work around."], bullets: ["Standardise evidence and controls where possible", "Localise accountability where required", "Record assumptions that depend on regulatory interpretation", "Use decision gates before irreversible investment"] },
      { id: "engagement", title: "Engage to understand, not to persuade", paragraphs: ["Early engagement with regulators is most useful when it tests understanding. The objective is to clarify mandate, process, evidence and areas of concern before the organisation commits to a position.", "This requires consistency between the external narrative and the internal plan. Regulators quickly see the gap when public commitments, product design and operating readiness do not align."], bullets: ["Prepare a precise description of the proposed service", "Ask where responsibility sits and what evidence is expected", "Track informal guidance without treating it as approval", "Keep product and operations teams close to the conversation"] },
    ], quote: "A regulatory map should sit beside the commercial model, not in a legal appendix.", takeaway: "Use regulation to shape market selection, sequencing and operating design from the beginning—not as a final permission check."
  },
  "cost-of-treating-africa-as-a-single-market": {
    image: "/images/intelligence/Blog thumbnail-Single market.avif", published: "24 July 2026",
    sections: [
      { id: "frame", title: "A portfolio frame is not an operating plan", paragraphs: ["Africa can be a useful portfolio frame: it focuses attention on long-term demographic, urban, technological and institutional shifts. It becomes less useful when it substitutes for a view of the specific markets in which a product, asset or team must operate.", "Customer behaviour, infrastructure, capital movement, regulatory authority and the speed of decision-making vary materially. These differences change the economics and the feasible route to growth."], bullets: ["Who the customer trusts and how they buy", "Which infrastructure is reliable enough to build on", "How institutions make and enforce decisions", "Where talent, capital and operational authority sit"] },
      { id: "cost", title: "The cost appears after commitment", paragraphs: ["A single-market assumption rarely fails in the strategy deck. It fails later, when a standard product does not fit, a regional partner lacks local influence or a central approval process slows the market team.", "By then, the organisation has often made public commitments, hired against the original model and built systems around assumptions that are expensive to change."], bullets: ["Product adaptation arrives late", "Partner performance is difficult to compare", "Local teams carry responsibility without authority", "Regional reporting hides different causes of underperformance"] },
      { id: "regional-model", title: "Build a regional model with explicit variation", paragraphs: ["A regional strategy is still possible. The strongest models define a common centre of gravity—brand, standards, capital discipline or shared infrastructure—while stating where local adaptation is expected.", "Compare markets on the factors that change the decision, not on every available indicator. This produces a smaller, more useful evidence base and makes trade-offs visible to senior leaders."], bullets: ["Standardise only where it creates measurable value", "Give local teams authority over defined variables", "Use comparable market evidence without forcing identical conclusions", "Review the regional model as conditions change"] },
    ], quote: "Africa is a useful frame for a portfolio conversation. It is rarely a useful operating plan.", takeaway: "Keep the regional ambition, but make local variation explicit in the product, partnership, authority and investment model."
  },
  "infrastructure-opportunities-beyond-major-cities": {
    image: "/images/intelligence/Blog thumbnail-Infrastructure-1.avif", published: "17 July 2026",
    sections: [
      { id: "connections", title: "Look at the connections between cities", paragraphs: ["Investment naturally gathers around the largest cities, where demand is visible and data is easier to obtain. Yet many durable opportunities sit in the systems connecting cities to producers, ports and consumers: warehousing, cold chains, freight interfaces, energy reliability and secondary distribution.", "These assets may be smaller individually, but their value can be tied to repeated operating needs rather than a single headline project."], bullets: ["Freight and storage serving multiple customer groups", "Cold-chain capacity close to production", "Reliable power for industrial and logistics clusters", "Interfaces that reduce time between transport modes"] },
      { id: "diligence", title: "Demand evidence must become more practical", paragraphs: ["Secondary-market demand is often real but dispersed. National growth forecasts are not enough to show who will use an asset, at what frequency and under which operating conditions.", "Diligence should follow the user journey through the network. Interviews, traffic observation, contracting behaviour and the economics of current alternatives can reveal demand that conventional datasets miss—or expose a forecast that depends on infrastructure not yet available."], bullets: ["Identify the actual user and payer", "Test the reliability of the supporting network", "Understand seasonal and route-specific variation", "Compare the asset with the customer’s current workaround"] },
      { id: "institutions", title: "Institutional decisions can determine utilisation", paragraphs: ["A commercially sound asset can remain underused when access roads, concessions, standards or public operating decisions do not align. These dependencies should be visible in the investment case rather than treated as external risks.", "The objective is not to eliminate institutional uncertainty. It is to identify the decisions that matter, who controls them and which commitments should wait until the evidence improves."], bullets: ["Map mandates and decision rights", "Separate formal approval from practical operating support", "Link capital stages to observable conditions", "Choose partners for operating capability as well as access"] },
    ], quote: "A more modest asset with the surrounding conditions in place can be stronger than a larger but isolated project.", takeaway: "Follow demand through the network, test the institutional dependencies and stage capital around evidence rather than headline asset size."
  },
  "digital-identity-public-infrastructure": {
    image: "/images/intelligence/Blog thumbnail-Digital Infrastructure.avif", published: "10 July 2026",
    sections: [
      { id: "service", title: "Start with the service problem", paragraphs: ["Digital identity is often discussed as a platform decision. Citizens experience it differently: as the ability to access a service, prove eligibility, open an account or avoid repeating the same information across institutions.", "Starting with a specific journey makes the value and the risks easier to see. It identifies who is excluded, where consent matters and what should happen when the system makes a mistake."], bullets: ["Choose a journey with visible public value", "Map every handoff and failure point", "Design an accessible alternative route", "Measure burden removed, not only enrolment"] },
      { id: "trust", title: "Trust is an operating requirement", paragraphs: ["A technically secure platform can still lose public trust if its purpose is unclear or accountability is fragmented. People need to understand what information is collected, how it will be used and who is responsible when something goes wrong.", "Trust therefore belongs in governance, service design and communications. It cannot be added through a campaign after the technical decisions have been made."], bullets: ["State purpose and limits in plain language", "Assign responsibility for correction and redress", "Publish service and privacy expectations", "Create oversight that citizens can recognise"] },
      { id: "rollout", title: "Build legitimacy through measured rollout", paragraphs: ["Large identity programmes create pressure for broad enrolment and ambitious launch dates. A measured rollout can produce stronger evidence by focusing first on services where trusted identification removes a real burden.", "Each stage should test technical reliability, institutional coordination and the citizen experience. Expansion then becomes a decision supported by evidence rather than momentum."], bullets: ["Pilot through one or two priority services", "Test agency roles before increasing scope", "Track exclusions and exceptions", "Expand standards and governance with usage"] },
    ], quote: "Digital identity succeeds when people can trust the service around the credential, not only the technology beneath it.", takeaway: "Anchor identity in a real service journey, make accountability visible and expand only as public value and operating reliability are demonstrated."
  },
  "signals-reshaping-east-african-logistics": {
    image: "/images/intelligence/Blog thumbnail-Cross border.avif", published: "3 July 2026",
    sections: [
      { id: "visibility", title: "1. Visibility is becoming part of the service", paragraphs: ["Customers increasingly judge logistics providers by the quality of information around a delivery, not only the final arrival time. A reliable estimate, early warning and clear explanation of an exception can be more valuable than an optimistic promise.", "Visibility requires common event definitions across operators, routes and systems. Without them, a dashboard may display activity without helping a customer make a decision."], bullets: ["Define the events customers need to act on", "Make exceptions visible early", "Measure the accuracy of estimates", "Give frontline teams a route to correct the record"] },
      { id: "border", title: "2. Border knowledge is an operating capability", paragraphs: ["Cross-border performance depends on documentation, classification, agency practice and the ability to resolve exceptions. This knowledge often sits with a few experienced individuals and disappears when the organisation scales.", "Operators can turn it into a repeatable capability by documenting decision paths, tracking recurring causes of delay and giving teams clear escalation rights."], bullets: ["Capture route-specific requirements", "Track causes rather than only duration", "Maintain accountable local relationships", "Design escalation around the authority to resolve"] },
      { id: "resilience", title: "3. Resilience is becoming a customer proposition", paragraphs: ["Customers are paying more attention to what happens when a route, port or partner fails. A network with credible recovery options can create confidence even if its standard transit time is not the fastest.", "Resilience should be designed before disruption. Alternate routes, capacity agreements and decision thresholds need commercial and operational owners."], bullets: ["Identify single points of failure", "Price and test recovery options", "Agree when to switch routes", "Communicate the trade-off before customers are affected"] },
    ], quote: "The opportunity is not only to move goods. It is to give customers confidence about when, how and under what conditions those goods will arrive.", takeaway: "Treat information, border-process knowledge and recovery options as core parts of the logistics proposition."
  },
  "local-context-and-strategy": {
    image: "/images/intelligence/Blog thumbnail-Market entry.avif", published: "26 June 2026",
    sections: [
      { id: "timing", title: "Context arrives too late", paragraphs: ["Local context is often commissioned after the market, product and investment case have already been selected. At that stage, insight can identify risks but has little room to change the route.", "The result is a familiar pattern: local teams inherit a plan built on regional assumptions, then spend the first months requesting exceptions. What appears to be an execution problem began as a sequencing problem."], bullets: ["Customer evidence gathered after product decisions", "Partner assessment after the route is fixed", "Regulatory engagement after public commitments", "Local leadership hired without decision authority"] },
      { id: "strategic-input", title: "Use context as a strategic input", paragraphs: ["Context is not a collection of cultural observations. It is evidence about the factors that change a decision: demand, trust, institutional authority, infrastructure, operating practice and the credibility of different routes.", "Bringing that evidence forward can reveal a better entry sequence, a narrower proposition or a partnership that changes the economics. It creates options rather than merely documenting risk."], bullets: ["Ask which assumptions are expensive if wrong", "Test them before irreversible commitment", "Compare evidence using decision-relevant factors", "Keep uncertainty visible in the recommendation"] },
      { id: "balance", title: "Standardise deliberately", paragraphs: ["Taking context seriously does not mean rebuilding every part of the organisation market by market. It means deciding explicitly what should remain common and what needs local variation.", "A useful operating model gives local teams authority over defined variables while protecting the standards that create regional value. The boundary should be reviewed as evidence accumulates."], bullets: ["Name the value created by each standard", "Define the variables local teams can change", "Set evidence thresholds for further adaptation", "Share learning across markets without forcing uniformity"] },
    ], quote: "Context can reveal a better route, not merely a risk to manage.", takeaway: "Move local evidence upstream, test the assumptions that can change the route and make the boundary between regional standards and local authority explicit."
  },
  "cross-border-expansion-research": {
    image: "/images/intelligence/Blog thumbnail-Single market.avif", published: "19 June 2026",
    sections: [
      { id: "method", title: "What this conceptual research examined", paragraphs: ["We reviewed fifty fictional market-entry journeys across payments, logistics, technology, financial services and infrastructure. The purpose was not to create a universal success rate, but to compare the decision patterns that appeared before and after commitment.", "The sample looked at sequencing, partner choice, local authority, regulatory dependencies and the evidence used to expand. Because the dataset is conceptual, the findings should be read as an editorial demonstration rather than empirical claims."], bullets: ["Five sectors and multiple market contexts", "Entry decisions from initial test to expansion", "Commercial, institutional and operating evidence", "Explicit attention to failure and adaptation"] },
      { id: "patterns", title: "Three patterns appeared repeatedly", paragraphs: ["The strongest entries did not move fastest at every stage. They made fewer early commitments, defined what they needed to learn and expanded when evidence supported the next move.", "They also treated partner choice and local authority as strategic design questions. Teams that carried responsibility without authority struggled to adapt, while partnerships chosen mainly for access often lacked the capability to deliver."], bullets: ["Partner choice is strategy, not procurement", "Local leadership needs authority as well as responsibility", "Launch conditions are more useful than a launch date", "Evidence should trigger expansion, adaptation or exit"] },
      { id: "discipline", title: "Decision discipline creates speed later", paragraphs: ["A staged approach can look slower at the beginning because it makes uncertainty visible. In practice, it reduces the rework created by premature commitments and gives leaders clearer reasons to continue or stop.", "The discipline lies in defining the test before seeing the result. Without that step, organisations interpret every signal as support for the direction they already prefer."], bullets: ["Write the learning question before the pilot", "Set decision thresholds and owners", "Keep sunk cost out of the next-stage decision", "Document what changed between markets"] },
    ], quote: "The strongest common pattern is not speed. It is decision discipline.", takeaway: "Make fewer early commitments, define the evidence required for the next stage and give local leaders authority to act on what the market reveals."
  },
};
